workflows:
  default:
    name: Flutter CI/CD
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: '*'
          include: true
    environment:
      groups:
        - google
      vars:
        GOOGLE_SERVICES_JSON: $GOOGLE_SERVICES_JSON
      flutter: stable
      xcode: latest
    scripts:
      - flutter pub get
      - echo '$GOOGLE_SERVICES_JSON' | base64 --decode > ./android/app/google-services.json
      - flutter build apk --release
