workflows:
  default:
    name: Flutter CI/CD
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: '*'
          include: true
    environment:
      groups:
        - google
      vars:
        GOOGLE_SERVICES_JSON: $GOOGLE_SERVICES_JSON
      flutter: 3.27.1
      xcode: latest
    scripts:
      - echo "$GOOGLE_SERVICES_JSON"
      - echo "$GOOGLE_SERVICES_JSON" | base64 -d > ./android/app/google-services.json  # base64 디코딩 후 파일로 출력
      - flutter pub get
      - flutter build apk --release
