// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM8BPBVzJCpImqd4JGq548JL7jGS0idDk',
    appId: '1:532512538480:web:c5190150c73cc6dbfad9b5',
    messagingSenderId: '532512538480',
    projectId: 'joseph-firebase',
    authDomain: 'joseph-firebase.firebaseapp.com',
    databaseURL: 'https://joseph-firebase-default-rtdb.firebaseio.com',
    storageBucket: 'joseph-firebase.firebasestorage.app',
    measurementId: 'G-28PVFWC142',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAldwCYRGKjcNTy2UMWMvN5ldNPSuq-pWU',
    appId: '1:532512538480:android:83dcf67146f35fa0fad9b5',
    messagingSenderId: '532512538480',
    projectId: 'joseph-firebase',
    databaseURL: 'https://joseph-firebase-default-rtdb.firebaseio.com',
    storageBucket: 'joseph-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBogOelBCU3F-E-bGWsACM6JWyV-P0EEYU',
    appId: '1:532512538480:ios:5083f206d45f3df7fad9b5',
    messagingSenderId: '532512538480',
    projectId: 'joseph-firebase',
    databaseURL: 'https://joseph-firebase-default-rtdb.firebaseio.com',
    storageBucket: 'joseph-firebase.firebasestorage.app',
    androidClientId: '532512538480-1un4e8kk4agm4l6uks3660oec2f8lnaf.apps.googleusercontent.com',
    iosClientId: '532512538480-glqoits859sa1gpnupcp44s3vltp2toq.apps.googleusercontent.com',
    iosBundleId: 'com.example.webProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBogOelBCU3F-E-bGWsACM6JWyV-P0EEYU',
    appId: '1:532512538480:ios:5083f206d45f3df7fad9b5',
    messagingSenderId: '532512538480',
    projectId: 'joseph-firebase',
    databaseURL: 'https://joseph-firebase-default-rtdb.firebaseio.com',
    storageBucket: 'joseph-firebase.firebasestorage.app',
    androidClientId: '532512538480-1un4e8kk4agm4l6uks3660oec2f8lnaf.apps.googleusercontent.com',
    iosClientId: '532512538480-glqoits859sa1gpnupcp44s3vltp2toq.apps.googleusercontent.com',
    iosBundleId: 'com.example.webProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDM8BPBVzJCpImqd4JGq548JL7jGS0idDk',
    appId: '1:532512538480:web:b0a700556fb500d1fad9b5',
    messagingSenderId: '532512538480',
    projectId: 'joseph-firebase',
    authDomain: 'joseph-firebase.firebaseapp.com',
    databaseURL: 'https://joseph-firebase-default-rtdb.firebaseio.com',
    storageBucket: 'joseph-firebase.firebasestorage.app',
    measurementId: 'G-NYQ8ZQTPTT',
  );
}
