name: Flutter CI

on:
    push:
        branches: 
            - '*'
    pull_request:
        branches:
            - personal_select_chat

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: 저장소 체크아웃
              uses: actions/checkout@v4

            - name: Flutter 설정
              uses: subosito/flutter-action@v2
              with:
                  flutter-version: 3.27.1
                  cache: true

            - name: 의존성 설치
              run: flutter pub get

            - name: Android Emulator 실행
              run: |
                echo "y" | sdkmanager "system-images;android-30;google_apis;x86_64"
                avdmanager create avd --name test --package "system-images;android-30;google_apis;x86_64" --device "Nexus 5X"
                emulator -avd test -no-audio -no-window &

            - name: ADB 연결 확인
              run: adb devices

            - name: 코드 포맷 검사
              run: dart format --set-exit-if-changed .

            - name: 분석 (Lint)
              run: flutter analyze

            - name: 유닛 테스트 & 위젯 테스트 실행
              run: flutter test test/login/login_widget_test.dart

            - name: 통합 테스트
              run: flutter test integration_test/app_flow_test.dart
