name: Flutter CI/CD

on:
  push:
    branches:
      - coin
  pull_request:
    branches:
      - coin

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Run tests
      run: flutter test

    - name: Build Flutter app
      run: flutter build apk --release  # Android 앱 빌드 (필요시 iOS 빌드로 변경 가능)

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifact
        path: build/app/outputs/flutter-apk/app-release.apk  # 빌드된 APK 파일 경로