name: Flutter CI

on:
  push:
    branches: [ "main" ]  # 'main' 브랜치에 푸시될 때마다 실행
  pull_request:
    branches: [ "main" ]  # 'main' 브랜치로 PR이 생성되거나 업데이트될 때 실행

jobs:
  build:
    runs-on: ubuntu-latest  # 우분투 환경에서 실행

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # 코드를 체크아웃합니다.

      - name: Set up Flutter
        uses: subosito/flutter-action@v2  # Flutter SDK 설정

      - name: Install dependencies
        run: flutter pub get  # Flutter 의존성 설치

      - name: Analyze code
        run: flutter analyze  # 코드 분석

      - name: Run tests
        run: flutter test  # Flutter 테스트 실행
