name: Flutter CI/CD

on:
  push:
    branches:
      - main   # main 브랜치에 푸시할 때마다 실행

jobs:
  build:
    runs-on: ubuntu-latest  # Ubuntu 환경에서 실행

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.0'  # 사용하려는 Flutter 버전

    - name: Install dependencies
      run: flutter pub get

    - name: Run tests
      run: flutter test  # 단위 테스트 실행

    - name: Build the app (Android)
      run: flutter build apk --release  # Android 빌드

    - name: Build the app (iOS)
      run: flutter build ios --release  # iOS 빌드